/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginsignup;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.mail.Message.RecipientType;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author sanjeev
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form forget
     */
    public ForgotPassword() {
        initComponents();
    }
    
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEmailAdd = new javax.swing.JTextField();
        jButtonSendMailpassword = new javax.swing.JButton();
        jButtonSendMailuserid = new javax.swing.JButton();
        jLabelResponse = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1147, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 223, 223));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("ENTER YOUR EMAIL :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(520, 140, 210, 34);

        jTextFieldEmailAdd.setFont(new java.awt.Font("Letter Gothic Std", 0, 16)); // NOI18N
        jTextFieldEmailAdd.setText("  xyz @ abc.com");
        jTextFieldEmailAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51), 3));
        jTextFieldEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailAddActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmailAdd);
        jTextFieldEmailAdd.setBounds(540, 220, 365, 48);

        jButtonSendMailpassword.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButtonSendMailpassword.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSendMailpassword.setText("forget password ?");
        jButtonSendMailpassword.setBorderPainted(false);
        jButtonSendMailpassword.setContentAreaFilled(false);
        jButtonSendMailpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendMailpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSendMailpassword);
        jButtonSendMailpassword.setBounds(730, 330, 200, 29);

        jButtonSendMailuserid.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButtonSendMailuserid.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSendMailuserid.setText("forget userid ?");
        jButtonSendMailuserid.setBorderPainted(false);
        jButtonSendMailuserid.setContentAreaFilled(false);
        jButtonSendMailuserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendMailuseridActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSendMailuserid);
        jButtonSendMailuserid.setBounds(540, 330, 160, 27);

        jLabelResponse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelResponse.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelResponse);
        jLabelResponse.setBounds(540, 400, 400, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginsignup/gmaillogo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 120, 430, 370);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(920, 20, 90, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailAddActionPerformed

    private void jButtonSendMailpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendMailpasswordActionPerformed
        
         Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", 465);
        props.put("mail.smtp.user", "ssanjeev9696@gmail.com");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.debug", "true");
        props.put("mail.smtp.socketFactory.port", 465);
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback", "false"); 
        try {
            Class.forName("com.mysql.jdbc.Driver");       
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
            String query = "select password from signup where email LIKE '"+jTextFieldEmailAdd.getText().trim()+"'";
           
            PreparedStatement statmntPASS = con.prepareStatement(query);
            ResultSet result = statmntPASS.executeQuery();       
           
            if (result.next())
            {   
                String fetchedPassword = result.getString("password"); 
                
                Session session = Session.getDefaultInstance(props, null);
                session.setDebug(true);
                MimeMessage message = new MimeMessage(session);
                message.setText("YOUR PASSWORD IS  - " + fetchedPassword);
                
                message.setSubject("MY PERSONAL PHONEBOOK ");
                message.setFrom(new InternetAddress("ssanjeev9696@gmail.com"));
                message.addRecipient(RecipientType.TO, new InternetAddress(jTextFieldEmailAdd.getText().trim()));
                message.saveChanges();
                Transport transport = session.getTransport("smtp");
                transport.connect("smtp.gmail.com", "ssanjeev9696@gmail.com", "29042000 SANJ");
                transport.sendMessage(message, message.getAllRecipients());
                transport.close();
                jLabelResponse.setText("Your password mailed to your email id");         
                
                
            }
        } catch (Exception e) {
            e.printStackTrace();  
            jLabelResponse.setText("Email Address not found");
            
        }  
        
    }//GEN-LAST:event_jButtonSendMailpasswordActionPerformed

    private void jButtonSendMailuseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendMailuseridActionPerformed
        
         Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", 465);
        props.put("mail.smtp.user", "ssanjeev9696@gmail.com");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.debug", "true");
        props.put("mail.smtp.socketFactory.port", 465);
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback", "false"); 
        try {
            Class.forName("com.mysql.jdbc.Driver");       
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
            String query = "select userid from signup where email LIKE '"+jTextFieldEmailAdd.getText().trim()+"'";
           
             PreparedStatement statmntuserid = con.prepareStatement(query);
            ResultSet result = statmntuserid.executeQuery();       
           
            if (result.next())
            {   
                String fetcheduserid = result.getString("userid"); 
                
                Session session = Session.getDefaultInstance(props, null);
                session.setDebug(true);
                MimeMessage message = new MimeMessage(session);
                message.setText("YOUR USER ID IS - " + fetcheduserid);
                
                message.setSubject("MY PERSONAL PHONEBOOK ");
                message.setFrom(new InternetAddress("ssanjeev9696@gmail.com"));
                message.addRecipient(RecipientType.TO, new InternetAddress(jTextFieldEmailAdd.getText().trim()));
                message.saveChanges();
                Transport transport = session.getTransport("smtp");
                transport.connect("smtp.gmail.com", "ssanjeev9696@gmail.com", "29042000 SANJ");
                transport.sendMessage(message, message.getAllRecipients());
                transport.close();
                jLabelResponse.setText("Your password mailed to your email id");         
            }
        } catch (Exception e) {
            e.printStackTrace();  
            jLabelResponse.setText("Email Address not found");
            
        }  
        
    }//GEN-LAST:event_jButtonSendMailuseridActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSendMailpassword;
    private javax.swing.JButton jButtonSendMailuserid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelResponse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEmailAdd;
    // End of variables declaration//GEN-END:variables
}
