/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginsignup;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sanjeev
 */
public class signupform extends javax.swing.JFrame {

    /**
     * Creates new form signupform2
     */
    public signupform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cpassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        cancle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1140, 790));
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1147, 710));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nueva Std", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText(" REGESTER HERE");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 80, 270, 50);

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email);
        email.setBounds(280, 480, 260, 50);

        fullname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel2.add(fullname);
        fullname.setBounds(280, 200, 260, 50);

        jLabel7.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("FULL NAME");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(100, 210, 130, 30);

        jLabel8.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("USER ID");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(100, 280, 90, 30);

        userID.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jPanel2.add(userID);
        userID.setBounds(280, 270, 260, 50);

        jLabel9.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText(" PASSWORD");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 350, 130, 30);

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passwordMouseReleased(evt);
            }
        });
        password.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                passwordInputMethodTextChanged(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        jPanel2.add(password);
        password.setBounds(280, 340, 260, 50);

        jLabel10.setFont(new java.awt.Font("Nueva Std", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("CONFIRM");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(100, 410, 80, 30);

        jLabel4.setFont(new java.awt.Font("Nueva Std", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("PASSWORD");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 430, 100, 30);

        Cpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(Cpassword);
        Cpassword.setBounds(280, 410, 260, 50);

        jLabel11.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("EMAIL ID");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(100, 500, 100, 30);

        submit.setBackground(new java.awt.Color(255, 255, 255));
        submit.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        submit.setText("SUBMIT");
        submit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel2.add(submit);
        submit.setBounds(430, 560, 110, 50);

        cancle.setBackground(new java.awt.Color(255, 255, 255));
        cancle.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        cancle.setText("cancle");
        cancle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        cancle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancleMouseClicked(evt);
            }
        });
        cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleActionPerformed(evt);
            }
        });
        jPanel2.add(cancle);
        cancle.setBounds(280, 560, 110, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginsignup/people.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(680, 200, 220, 260);

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginsignup/web8.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 40, 970, 610);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1100, 720);

        setSize(new java.awt.Dimension(1122, 773));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        new login().setVisible(false);
        
        String name =fullname.getText();
        String userid = userID.getText();

        String pass = String.valueOf(password.getPassword());
        String cpass = String.valueOf(Cpassword.getText());
        
        
        
        String mail = email.getText();
        
                  
        if(name.equals(""))
        {
            JOptionPane.showMessageDialog(null,"ENTER NAME ","ERROR",JOptionPane.ERROR_MESSAGE);
        } 
              
        else if(userid.equals(""))
        {
            JOptionPane.showMessageDialog(null,"ENTER USERID ","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        else if(cheakusername(userid))
        {
            JOptionPane.showMessageDialog(null,"THIS USER NAME IS ALREADY EXIST");
        }
        else if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null,"ENTER VALID PASSWORD/","ERROR",JOptionPane.ERROR_MESSAGE);
        }
       
        
        else if(cpass == null ? pass != null : !cpass.equals(pass))
              {
            JOptionPane.showMessageDialog(null, "PASSWORD DOES NOT MATCH","ERROR" , JOptionPane.ERROR_MESSAGE);
               
              }
         
            
        
        else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email.getText())))
        
         { JOptionPane.showMessageDialog(null, "PLEASE ENTER VAILED EMAIL", "Error", JOptionPane.ERROR_MESSAGE); 
        
        }
        
        else { PreparedStatement pst;
        
        String query="INSERT INTO `signup`(`name`, `userid`, `password`, `email`) VALUES (?,?,?,?)";
        
        try {
                pst=insertdata.getdata().prepareStatement(query);
            
                pst.setString(1,name);
                pst.setString(2,userid); 
                pst.setString(3,pass);
                pst.setString(4,mail);
               
               if (pst.executeUpdate()>0)
                       {
                           JOptionPane.showMessageDialog(null,"DATA SAVED SUCESSFULLY");
                           setVisible(false);
                           new login().setVisible(true);
                           
                             
                       }
               
        } 
        
         catch (SQLException ex) {
            Logger.getLogger(signupform.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
         
    }//GEN-LAST:event_submitActionPerformed

    public boolean cheakusername(String username){
    
         PreparedStatement pst;
      ResultSet res;
      boolean cheak = false;
      
       String query="SELECT * FROM `signup` WHERE `userid`=?";
       
       try
       {pst=insertdata.getdata().prepareStatement(query);
        pst.setString(1,username);
        
       res=pst.executeQuery();
            
            if(res.next())
            {
             cheak = false;   
            }
       
           
       }
       catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
            
       return cheak;
       
  
    
}
    
    
    
    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed

    }//GEN-LAST:event_emailActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitMouseClicked

    private void cancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancleMouseClicked

    private void cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleActionPerformed
        // TODO add your handling code here:
         new login().setVisible(true);
         this.setVisible(false);
         
         
    }//GEN-LAST:event_cancleActionPerformed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
        
        if(password.getText().length()>10)
        {
            JOptionPane.showMessageDialog(null,"PASSWORD LENGTH MUST BE LESS THE 10 LETTERS ","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_passwordKeyReleased

    private void passwordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_passwordInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passwordInputMethodTextChanged

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passwordKeyTyped

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_passwordKeyPressed

    private void passwordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passwordMouseReleased

    private void passwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passwordMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Cpassword;
    javax.swing.JButton cancle;
    public javax.swing.JTextField email;
    public javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPasswordField password;
    javax.swing.JButton submit;
    public javax.swing.JTextField userID;
    // End of variables declaration//GEN-END:variables
}
