/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import loginsignup.insertdata;
import loginsignup.signupform;
import java.lang.String;
import java.util.regex.Pattern;

/**
 *
 * @author sanjeev
 */
public class add extends javax.swing.JFrame {

    /**
     * Creates new form add
     */
    public add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooserimage = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldcnt = new javax.swing.JTextField();
        jTextFieldgml = new javax.swing.JTextField();
        jTextFieldadd = new javax.swing.JTextField();
        jTextFieldimg = new javax.swing.JTextField();
        jTextFieldname = new javax.swing.JTextField();
        jLabelshowimg = new javax.swing.JLabel();
        jButtonbrowse = new javax.swing.JButton();
        jButtonsave = new javax.swing.JButton();
        jButtonsave1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonfemale = new javax.swing.JRadioButton();
        jRadioButtonmale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ADD CONTACT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldcnt.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldcnt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldcnt.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldcnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcntActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldcnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 405, 322, 57));

        jTextFieldgml.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldgml.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldgml.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldgml, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 332, 322, 57));

        jTextFieldadd.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldadd.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 480, 322, 57));

        jTextFieldimg.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldimg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldimg.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 555, 322, 57));

        jTextFieldname.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 171, 322, 57));

        jLabelshowimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/peopleinvert.png"))); // NOI18N
        jPanel1.add(jLabelshowimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 195, 230, 250));

        jButtonbrowse.setText("Browse...");
        jButtonbrowse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbrowseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonbrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 568, 97, 32));

        jButtonsave.setBackground(new java.awt.Color(204, 204, 255));
        jButtonsave.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jButtonsave.setText("Save");
        jButtonsave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 630, 100, 40));

        jButtonsave1.setBackground(new java.awt.Color(204, 204, 255));
        jButtonsave1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jButtonsave1.setText("Back");
        jButtonsave1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsave1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 100, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Gender");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 270, 109, 49));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Email ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 349, 109, 49));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Contact No.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 424, -1, 49));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 179, 109, 49));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Upload image");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 565, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("City or Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 488, -1, 49));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("( if any )");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 593, -1, 28));

        jRadioButtonfemale.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(jRadioButtonfemale);
        jRadioButtonfemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonfemale.setText("female");
        jRadioButtonfemale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jRadioButtonfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 260, 138, 54));

        jRadioButtonmale.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(jRadioButtonmale);
        jRadioButtonmale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonmale.setText("male");
        jRadioButtonmale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jRadioButtonmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 260, 126, 54));

        jLabel9.setText("img size 226*246 only");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 140, 20));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1150, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1170, 700));

        setSize(new java.awt.Dimension(1224, 779));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsaveActionPerformed
        // TODO add your handling code here:
         String name=jTextFieldname.getText();
        String gender="";
                if(jRadioButtonmale.isSelected()==true)
                    gender ="male";
                else
                    gender="female";
                            
                
        String mailid=jTextFieldgml.getText();
        String contact=jTextFieldcnt.getText();
        String address=jTextFieldadd.getText();
        String imgurl=jTextFieldimg.getText();
        
       if(name=="")
       {
           
          JOptionPane.showMessageDialog(null,"ENTER NAME","ERROR",JOptionPane.ERROR_MESSAGE);
       }
       
       else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+", jTextFieldgml.getText())))
        
        { JOptionPane.showMessageDialog(null, "PLEASE ENTER VAILED EMAIL", "Error", JOptionPane.ERROR_MESSAGE); 
        
        }
        else if(!(Pattern.matches("^[0-9]+$",jTextFieldcnt.getText())))
        {
          
          JOptionPane.showMessageDialog(null,"ENTER A VALID PHONE NUMBER","Error",JOptionPane.ERROR_MESSAGE);
                     
        }
        
        else if(address=="")
        {
            
          JOptionPane.showMessageDialog(null,"Enter city","error",JOptionPane.ERROR_MESSAGE);
        }
            
        else{
        
        PreparedStatement ps ;
        String query ="INSERT INTO `contactbook`(`name`, `gender`, `mailid`, `contact`, `address`,`imageurl`) VALUES (?,?,?,?,?,?)";
        
        try {
            
            ps = insertdata.getdata().prepareStatement(query);
            
            ps.setString(1,name);
            ps.setString(2,gender);
            ps.setString(3,mailid);
            ps.setString(4,contact);
            ps.setString(5,address);
            ps.setString(6,imgurl);
            
              if (ps.executeUpdate()>0)
                       {
                           JOptionPane.showMessageDialog(null,"DATA SAVED SUCESSFULLY");
                                                      
                          
                           new menu().setVisible(true);
                           this.setVisible(false);
                                                        
                       }
              
        } catch (SQLException e) {
             Logger.getLogger(signupform.class.getName()).log(Level.SEVERE, null, e);
        }
        
        }
        
        
        
        
    }//GEN-LAST:event_jButtonsaveActionPerformed

    private void jButtonbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbrowseActionPerformed
        // TODO add your handling code here:
        try{
       int givevalue=jFileChooserimage.showOpenDialog(this);
       FileFilter select= new FileNameExtensionFilter("JPEG file","jpg","jpeg");
       jFileChooserimage.setFileFilter(select);
       
       if(givevalue==jFileChooserimage.APPROVE_OPTION)
       {
           String path=jFileChooserimage.getSelectedFile().getPath();
           jTextFieldimg.setText(path);
           jLabelshowimg.setIcon(new javax.swing.ImageIcon(path));
           
       }
       
        
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(this,"ERROR!! choose only jpg or JPEG file");   
        }
    }//GEN-LAST:event_jButtonbrowseActionPerformed

    private void jTextFieldcntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcntActionPerformed

    private void jButtonsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsave1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_jButtonsave1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonbrowse;
    private javax.swing.JButton jButtonsave;
    private javax.swing.JButton jButtonsave1;
    private javax.swing.JFileChooser jFileChooserimage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelshowimg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonfemale;
    private javax.swing.JRadioButton jRadioButtonmale;
    private javax.swing.JTextField jTextFieldadd;
    private javax.swing.JTextField jTextFieldcnt;
    private javax.swing.JTextField jTextFieldgml;
    private javax.swing.JTextField jTextFieldimg;
    private javax.swing.JTextField jTextFieldname;
    // End of variables declaration//GEN-END:variables

  
}
