/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import loginsignup.insertdata;
import loginsignup.signupform;

/**
 *
 * @author sanjeev
 */
public class admin_control_panel extends javax.swing.JFrame {

    /**
     * Creates new form admin_control_panel
     */
    public admin_control_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        admpass = new java.awt.TextField();
        acesspanelm = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        userID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        Cpassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        newpass = new javax.swing.JTextField();
        newpass1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cancle = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("Admin access panel");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 13, 312, 44);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("GO");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(670, 130, 57, 40);

        admpass.setBackground(new java.awt.Color(0, 51, 51));
        admpass.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        admpass.setForeground(new java.awt.Color(255, 255, 255));
        admpass.setText("enter admin password again to access");
        admpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admpassActionPerformed(evt);
            }
        });
        jPanel1.add(admpass);
        admpass.setBounds(323, 129, 350, 40);

        acesspanelm.setBackground(new java.awt.Color(0, 51, 51));
        acesspanelm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADMIN CONTROLE PANEL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        acesspanelm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Nueva Std", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("CONFERM NEW  PASSWORD");
        acesspanelm.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 180, 30));

        fullname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        acesspanelm.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 30));

        jLabel8.setFont(new java.awt.Font("Nueva Std", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("USER ID");
        acesspanelm.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, 90, 30));

        userID.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        acesspanelm.add(userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, 30));

        jLabel9.setFont(new java.awt.Font("Nueva Std", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText(" PASSWORD");
        acesspanelm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 190, 90, -1));

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        acesspanelm.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 142, 30));

        jLabel10.setFont(new java.awt.Font("Nueva Std", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("CONFIRM");
        acesspanelm.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 223, 80, 30));

        Cpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        acesspanelm.add(Cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, 30));

        jLabel11.setFont(new java.awt.Font("Nueva Std", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("EMAIL ID");
        acesspanelm.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 260, 64, 30));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        acesspanelm.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 140, 30));

        submit.setBackground(new java.awt.Color(204, 255, 255));
        submit.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        submit.setText("SUBMIT");
        submit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        submit.setBorderPainted(false);
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        acesspanelm.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 70, 30));

        jLabel2.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("CHANGE PASSWORD");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        acesspanelm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 220, -1));

        jLabel4.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ADD ADMIN");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        acesspanelm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 135, -1));

        jLabel12.setFont(new java.awt.Font("Nueva Std", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("FULL NAME");
        acesspanelm.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 99, 85, 30));

        newpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });
        acesspanelm.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 260, 30));

        newpass1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpass1ActionPerformed(evt);
            }
        });
        acesspanelm.add(newpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 260, 30));

        jLabel13.setFont(new java.awt.Font("Nueva Std", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("ENTER NEW PASSWORD");
        acesspanelm.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 150, 30));

        jPanel1.add(acesspanelm);
        acesspanelm.setBounds(20, 260, 1030, 370);

        cancle.setBackground(new java.awt.Color(204, 255, 255));
        cancle.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        cancle.setText("exit");
        cancle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        cancle.setBorderPainted(false);
        cancle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancleMouseClicked(evt);
            }
        });
        cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleActionPerformed(evt);
            }
        });
        jPanel1.add(cancle);
        cancle.setBounds(960, 10, 70, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1090, 695);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       String adminpass= admpass.getText();
       PreparedStatement pst;
       ResultSet res ;
       
        String query = "SELECT * FROM `signup` WHERE `password`=?";
        
        try {
            
              pst=insertdata.getdata().prepareStatement(query);
            
              pst.setString(1,adminpass);
              
              res=pst.executeQuery();
              
              
              if(res.next())
              {
                  JOptionPane.showConfirmDialog(null,"ENTER ADMIN PANEL");
                 acesspanelm.setVisible(true);
              }
               else
            {
                 JOptionPane.showMessageDialog(null," ENTER VAILED PASSWORD","ERROR",JOptionPane.ERROR_MESSAGE);
            }
              
        } catch (Exception e) {
        }
           
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void admpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admpassActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        

        String name =fullname.getText();
        String userid = userID.getText();

        String pass = String.valueOf(password.getPassword());
        String cpass = String.valueOf(Cpassword.getText());

        String mail = email.getText();

        if(name.equals(""))
        {
            JOptionPane.showMessageDialog(null,"ENTER NAME ","ERROR",JOptionPane.ERROR_MESSAGE);
        }

        else if(userid.equals(""))
        {
            JOptionPane.showMessageDialog(null,"ENTER USERID ","ERROR",JOptionPane.ERROR_MESSAGE);
        }

        
        else if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null,"ENTER PASSWORD","ERROR",JOptionPane.ERROR_MESSAGE);
        }

        else if(cpass == null ? pass != null : !cpass.equals(pass))
        {
            JOptionPane.showMessageDialog(null, "PASSWORD DOES NOT MATCH","ERROR" , JOptionPane.ERROR_MESSAGE);

        }

        else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$",email.getText())))

        { JOptionPane.showMessageDialog(null, "PLEASE ENTER VAILED EMAIL", "Error", JOptionPane.ERROR_MESSAGE);

        }

        else { PreparedStatement pst;

            String query="INSERT INTO `signup`(`name`, `userid`, `password`, `email`) VALUES (?,?,?,?)";

            try {
                pst=insertdata.getdata().prepareStatement(query);

                pst.setString(1,name);
                pst.setString(2,userid);
                pst.setString(3,pass);
                pst.setString(4,mail);

                if (pst.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null,"NEW ADMIN ADDEDE");
                    

                }

            }

            catch (SQLException ex) {
                Logger.getLogger(signupform.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_submitActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitMouseClicked

    private void cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleActionPerformed
        // TODO add your handling code here:
       
        this.setVisible(false);
        new menu().setVisible(true);
        
        
    }//GEN-LAST:event_cancleActionPerformed

    private void cancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancleMouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed

    }//GEN-LAST:event_emailActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void newpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_control_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_control_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_control_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_control_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               
          
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cpassword;
    javax.swing.JPanel acesspanelm;
    private java.awt.TextField admpass;
    javax.swing.JButton cancle;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newpass;
    private javax.swing.JTextField newpass1;
    private javax.swing.JPasswordField password;
    javax.swing.JButton submit;
    private javax.swing.JTextField userID;
    // End of variables declaration//GEN-END:variables
}
