/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import loginsignup.insertdata;
import loginsignup.login;

/**
 *
 * @author sanjeev
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
     DefaultTableModel model;
    public menu() {
        initComponents();
        showuser();
    }
    
    ArrayList<User> userlist(){
      
        ArrayList<User> userslist = new ArrayList<>();
        
          PreparedStatement ps ;
 
   
       
        
       
        try {
           
            Class.forName("com.mysql.jdbc.Driver");
            
          Connection  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
          
          String query1="SELECT * FROM `contactbook` ";
          Statement st= con.createStatement();
          ResultSet rs = st.executeQuery(query1);
             
          User user;
          
          while(rs.next())
          {
              
           user = new User(rs.getString("contact"),rs.getString("name"),rs.getString("gender"),rs.getString("mailid"),rs.getString("address"));  // in correct order where class user was taking argument
           userslist.add(user);
              
          }
                
            } 
        
         catch (Exception e) 
            {
             System.out.println(e.getMessage());
             
            }
      return userslist;
     
       
    }
    
    public void showuser()
    {
        
        ArrayList<User> list = userlist();
        
         model = (DefaultTableModel) dataTable.getModel();
        Object []row = new Object[3];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getName();
            row[1]=list.get(i).getContact();
            row[2]=list.get(i).getaddress();
            model.addRow(row);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanemain = new javax.swing.JDesktopPane();
        inputsection = new javax.swing.JPanel();
        searchpanel = new javax.swing.JPanel();
        fieldname = new javax.swing.JComboBox<>();
        value = new javax.swing.JTextField();
        detail = new javax.swing.JPanel();
        nameout = new javax.swing.JLabel();
        cityout = new javax.swing.JLabel();
        contactout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addnew = new javax.swing.JButton();
        admincontrole = new javax.swing.JButton();
        admincontrole1 = new javax.swing.JButton();
        tablepannel = new javax.swing.JPanel();
        jButtondelete = new javax.swing.JButton();
        dataTable = new javax.swing.JTable();
        jButtonveiw = new javax.swing.JButton();
        backup = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPanemain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jDesktopPanemain.setForeground(new java.awt.Color(255, 255, 255));

        inputsection.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        inputsection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchpanel.setBackground(new java.awt.Color(0, 51, 51));
        searchpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        fieldname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fieldname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "contact", "city", " " }));
        fieldname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        value.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });
        value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valueKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout searchpanelLayout = new javax.swing.GroupLayout(searchpanel);
        searchpanel.setLayout(searchpanelLayout);
        searchpanelLayout.setHorizontalGroup(
            searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        searchpanelLayout.setVerticalGroup(
            searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        inputsection.add(searchpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 460, 200));

        detail.setBackground(new java.awt.Color(0, 51, 51));
        detail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETAIL VIEW", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        detail.setForeground(new java.awt.Color(0, 51, 51));

        nameout.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        nameout.setForeground(new java.awt.Color(204, 204, 204));

        cityout.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        cityout.setForeground(new java.awt.Color(204, 204, 204));

        contactout.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        contactout.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout detailLayout = new javax.swing.GroupLayout(detail);
        detail.setLayout(detailLayout);
        detailLayout.setHorizontalGroup(
            detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cityout, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactout, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameout, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        detailLayout.setVerticalGroup(
            detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nameout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cityout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        inputsection.add(detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 460, 270));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADMIN CONTROL PANEL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        addnew.setBackground(new java.awt.Color(153, 153, 153));
        addnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addnew.setForeground(new java.awt.Color(51, 51, 51));
        addnew.setText("ADD NEW CONTACT");
        addnew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 153, 153)));
        addnew.setBorderPainted(false);
        addnew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addnew.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        addnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addnewMouseClicked(evt);
            }
        });
        addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewActionPerformed(evt);
            }
        });

        admincontrole.setBackground(new java.awt.Color(153, 153, 153));
        admincontrole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admincontrole.setForeground(new java.awt.Color(51, 51, 51));
        admincontrole.setText("ADD ADMIN");
        admincontrole.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admincontrole.setBorderPainted(false);
        admincontrole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admincontroleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admincontroleMouseEntered(evt);
            }
        });
        admincontrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admincontroleActionPerformed(evt);
            }
        });
        admincontrole.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                admincontroleKeyPressed(evt);
            }
        });

        admincontrole1.setBackground(new java.awt.Color(153, 153, 153));
        admincontrole1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admincontrole1.setForeground(new java.awt.Color(51, 51, 51));
        admincontrole1.setText("Signout");
        admincontrole1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admincontrole1.setBorderPainted(false);
        admincontrole1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admincontrole1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admincontrole1MouseEntered(evt);
            }
        });
        admincontrole1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admincontrole1ActionPerformed(evt);
            }
        });
        admincontrole1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                admincontrole1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(admincontrole1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admincontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addnew, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addnew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(admincontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(admincontrole1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        inputsection.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 460, 210));

        tablepannel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CONTECT LIST", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        tablepannel.setForeground(new java.awt.Color(51, 51, 51));
        tablepannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtondelete.setText("delete");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });
        tablepannel.add(jButtondelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 730, 144, 40));

        dataTable.setBackground(new java.awt.Color(0, 51, 51));
        dataTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        dataTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dataTable.setForeground(new java.awt.Color(255, 255, 255));
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"NAME", "CONTACT NO.", "CITY"},
                {null, null, null}
            },
            new String [] {
                "NAME", "CONTACT NO.", "CITY"
            }
        ));
        dataTable.getTableHeader().setReorderingAllowed(false);
        tablepannel.add(dataTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 540, 700));
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(2).setHeaderValue("CITY");
        }

        jButtonveiw.setText("View");
        jButtonveiw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonveiwActionPerformed(evt);
            }
        });
        tablepannel.add(jButtonveiw, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 144, 40));

        backup.setText("Backup");
        backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupActionPerformed(evt);
            }
        });
        tablepannel.add(backup, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 730, 144, 40));

        jDesktopPanemain.setLayer(inputsection, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanemain.setLayer(tablepannel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanemainLayout = new javax.swing.GroupLayout(jDesktopPanemain);
        jDesktopPanemain.setLayout(jDesktopPanemainLayout);
        jDesktopPanemainLayout.setHorizontalGroup(
            jDesktopPanemainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanemainLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(inputsection, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(tablepannel, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jDesktopPanemainLayout.setVerticalGroup(
            jDesktopPanemainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanemainLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jDesktopPanemainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tablepannel, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addComponent(inputsection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        inputsection.getAccessibleContext().setAccessibleName("INSERT SECTION");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(120, 32769));
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPanemain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanemain)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewActionPerformed
        
      this.setVisible(false);
       new add().setVisible(true);  
      
       
      
        
    }//GEN-LAST:event_addnewActionPerformed

    private void filter(String query)
    {
        TableRowSorter<DefaultTableModel> tr = new  TableRowSorter<DefaultTableModel>(model);
         dataTable.setRowSorter(tr);
         tr.setRowFilter(RowFilter.regexFilter(query));
        
    }
    
    
    
    private void addnewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addnewMouseClicked

           
    }//GEN-LAST:event_addnewMouseClicked

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueActionPerformed

    private void valueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valueKeyReleased
        
        String query = value.getText().toLowerCase();
        filter(query);
        
        
        
    }//GEN-LAST:event_valueKeyReleased

    private void jButtonveiwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonveiwActionPerformed
        // TODO add your handling code here:
      
        int rowindex= dataTable.getSelectedRow();
        
        
                
        nameout.setText(model.getValueAt(rowindex,0).toString());
         contactout.setText(model.getValueAt(rowindex,1).toString());
          cityout.setText(model.getValueAt(rowindex,2).toString());
           
       
       
    }//GEN-LAST:event_jButtonveiwActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        
        try {
            int selectrow = dataTable.getSelectedRow();
            model.removeRow(selectrow);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupActionPerformed
    MessageFormat headerFmt = new MessageFormat("Notebook"),
                      footerFmt = new MessageFormat("Page {0}");

        JTable.PrintMode printMode = JTable.PrintMode.FIT_WIDTH;

        try {
            boolean status = dataTable.print(printMode, headerFmt, footerFmt);

            if (status) {
                JOptionPane.showMessageDialog(dataTable.getParent(), "printing is Complete",
                                              "printing Result", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(dataTable.getParent(),  "printing Cancelled",
                                              "printing Result",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (PrinterException pe) {
            String errorMessage = MessageFormat.format("printing Failed",  new Object[] {pe.getMessage()});
            JOptionPane.showMessageDialog(dataTable.getParent(),  errorMessage,
                                          "printing Result",  JOptionPane.ERROR_MESSAGE);
        } catch (SecurityException se) {
            String errorMessage = MessageFormat.format("printing Failed", new Object[] {se.getMessage()});
            JOptionPane.showMessageDialog(dataTable.getParent(),   errorMessage,
                                          "TableDemo.printingResult",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_backupActionPerformed

    private void admincontroleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admincontroleMouseClicked
        // TODO add your handling code here:
          admin_control_panel acp = new admin_control_panel();
          
          acp.setVisible(true);
          acp.acesspanelm.setVisible(false);
         
    }//GEN-LAST:event_admincontroleMouseClicked

    private void admincontroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admincontroleActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         admin_control_panel acp = new admin_control_panel();
      
          acp.setVisible(true);
              acp.acesspanelm.setVisible(false);
    }//GEN-LAST:event_admincontroleActionPerformed

    private void admincontroleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admincontroleMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_admincontroleMouseEntered

    private void admincontroleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admincontroleKeyPressed
        // TODO add your handling code here:
          admin_control_panel acp = new admin_control_panel();
         
          acp.setVisible(true);
           acp.acesspanelm.setVisible(false);
    }//GEN-LAST:event_admincontroleKeyPressed

    private void admincontrole1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admincontrole1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_admincontrole1MouseClicked

    private void admincontrole1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admincontrole1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_admincontrole1MouseEntered

    private void admincontrole1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admincontrole1ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_admincontrole1ActionPerformed

    private void admincontrole1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admincontrole1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_admincontrole1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnew;
    private javax.swing.JButton admincontrole;
    private javax.swing.JButton admincontrole1;
    private javax.swing.JButton backup;
    private javax.swing.JLabel cityout;
    private javax.swing.JLabel contactout;
    private javax.swing.JTable dataTable;
    private javax.swing.JPanel detail;
    private javax.swing.JComboBox<String> fieldname;
    private javax.swing.JPanel inputsection;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonveiw;
    private javax.swing.JDesktopPane jDesktopPanemain;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameout;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JPanel tablepannel;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
